{
  "Morph": {
    "type": "programming",
    "color": "#ff6b35",
    "extensions": [".fox"],
    "tm_scope": "source.morph",
    "ace_mode": "text",
    "language_id": 999999,
    "aliases": ["morph"],
    "filenames": [],
    "interpreters": ["morph"],
    "group": "Morph"
  },
  "Elsa": {
    "type": "prose",
    "color": "#4fc1ff",
    "extensions": [".elsa"],
    "tm_scope": "text.html.elsa",
    "ace_mode": "markdown",
    "language_id": 999998,
    "aliases": ["elsa", "morph-docs"],
    "filenames": ["README.elsa"],
    "group": "Morph"
  }
}
